/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnistub_AuthAnonymousStub */

#ifndef _Included_jnistub_AuthAnonymousStub
#define _Included_jnistub_AuthAnonymousStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnistub_AuthAnonymousStub
 * Method:    onAuthenticated
 * Signature: (JLcom/firebase/client/AuthData;)V
 */
JNIEXPORT void JNICALL Java_jnistub_AuthAnonymousStub_onAuthenticated
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jnistub_AuthAnonymousStub
 * Method:    onAuthenticationError
 * Signature: (JLcom/firebase/client/FirebaseError;)V
 */
JNIEXPORT void JNICALL Java_jnistub_AuthAnonymousStub_onAuthenticationError
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
