/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnistub_AuthCustomTokenStub */

#ifndef _Included_jnistub_AuthCustomTokenStub
#define _Included_jnistub_AuthCustomTokenStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnistub_AuthCustomTokenStub
 * Method:    onAuthenticated
 * Signature: (JLcom/firebase/client/AuthData;)V
 */
JNIEXPORT void JNICALL Java_jnistub_AuthCustomTokenStub_onAuthenticated
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jnistub_AuthCustomTokenStub
 * Method:    onAuthenticationError
 * Signature: (JLcom/firebase/client/FirebaseError;)V
 */
JNIEXPORT void JNICALL Java_jnistub_AuthCustomTokenStub_onAuthenticationError
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
