/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnistub_ValueEventListenerStub */

#ifndef _Included_jnistub_ValueEventListenerStub
#define _Included_jnistub_ValueEventListenerStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnistub_ValueEventListenerStub
 * Method:    onDataChange
 * Signature: (JLcom/firebase/client/DataSnapshot;)V
 */
JNIEXPORT void JNICALL Java_jnistub_ValueEventListenerStub_onDataChange
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jnistub_ValueEventListenerStub
 * Method:    onCancelled
 * Signature: (JLcom/firebase/client/FirebaseError;)V
 */
JNIEXPORT void JNICALL Java_jnistub_ValueEventListenerStub_onCancelled
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
