/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnistub_AuthOAuthStub */

#ifndef _Included_jnistub_AuthOAuthStub
#define _Included_jnistub_AuthOAuthStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnistub_AuthOAuthStub
 * Method:    onAuthenticated
 * Signature: (JLcom/firebase/client/AuthData;)V
 */
JNIEXPORT void JNICALL Java_jnistub_AuthOAuthStub_onAuthenticated
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jnistub_AuthOAuthStub
 * Method:    onAuthenticationError
 * Signature: (JLcom/firebase/client/FirebaseError;)V
 */
JNIEXPORT void JNICALL Java_jnistub_AuthOAuthStub_onAuthenticationError
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
