/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnistub_ChildEventListenerStub */

#ifndef _Included_jnistub_ChildEventListenerStub
#define _Included_jnistub_ChildEventListenerStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnistub_ChildEventListenerStub
 * Method:    onChildAdded
 * Signature: (JLcom/firebase/client/DataSnapshot;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jnistub_ChildEventListenerStub_onChildAdded
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     jnistub_ChildEventListenerStub
 * Method:    onChildChanged
 * Signature: (JLcom/firebase/client/DataSnapshot;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jnistub_ChildEventListenerStub_onChildChanged
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     jnistub_ChildEventListenerStub
 * Method:    onChildRemoved
 * Signature: (JLcom/firebase/client/DataSnapshot;)V
 */
JNIEXPORT void JNICALL Java_jnistub_ChildEventListenerStub_onChildRemoved
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jnistub_ChildEventListenerStub
 * Method:    onChildMoved
 * Signature: (JLcom/firebase/client/DataSnapshot;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jnistub_ChildEventListenerStub_onChildMoved
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     jnistub_ChildEventListenerStub
 * Method:    onCancelled
 * Signature: (JLcom/firebase/client/FirebaseError;)V
 */
JNIEXPORT void JNICALL Java_jnistub_ChildEventListenerStub_onCancelled
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
